"""Deterministik haber demosu için aynı gelişmenin farklı kaynak görünümleri.

Metinler gerçek zamanlı haber iddiası taşımaz; yarışma demosu için hazırlanmış
örnek içeriklerdir. Her olayın temel olguları iki kaynakta da korunur. İkinci
kaynak yalnızca çözüm, bağlam veya ilerleme tarafını daha görünür kılar.
"""

HABERLER = [
    {
        "id": "iklim-a", "olay_id": "iklim", "birincil": True,
        "kaynak": "Gündem 24", "kaynak_kodu": "G24", "kategori": "Çevre",
        "baslik": "Kentte aşırı yağış ulaşımı aksattı",
        "ozet": "Sabah saatlerindeki yoğun yağış bazı ana yollarda kısa süreli su birikintilerine neden oldu.",
        "cerceve": "anlık gelişme", "duygu": -0.62, "gorsel": "/assets/explore/03-city.jpg",
        "zaman": "18 dk", "alternatif_id": "iklim-b", "olgu_kodu": "yagis-ulasim-1",
    },
    {
        "id": "iklim-b", "olay_id": "iklim", "birincil": False,
        "kaynak": "Kent Çözümleri", "kaynak_kodu": "KÇ", "kategori": "Çevre",
        "baslik": "Aynı yağışta yeni tahliye hatları üç bölgede devreye girdi",
        "ozet": "Ulaşım aksamaları sürerken belediye ekipleri yeni tahliye noktalarının suyun çekilmesini hızlandırdığını bildirdi.",
        "cerceve": "çözüm ve ilerleme", "duygu": 0.34, "gorsel": "/assets/explore/03-city.jpg",
        "zaman": "12 dk", "alternatif_id": "iklim-a", "olgu_kodu": "yagis-ulasim-1",
    },
    {
        "id": "enerji-a", "olay_id": "enerji", "birincil": True,
        "kaynak": "Ekonomi Hattı", "kaynak_kodu": "EH", "kategori": "Ekonomi",
        "baslik": "Enerji maliyetlerindeki artış küçük işletmeleri zorluyor",
        "ozet": "İşletmeler son çeyrekte artan enerji giderlerinin bütçelerinde baskı oluşturduğunu belirtiyor.",
        "cerceve": "ekonomik baskı", "duygu": -0.55, "gorsel": "/assets/explore/15-market.jpg",
        "zaman": "31 dk", "alternatif_id": "enerji-b", "olgu_kodu": "enerji-kobi-1",
    },
    {
        "id": "enerji-b", "olay_id": "enerji", "birincil": False,
        "kaynak": "Üretim Notları", "kaynak_kodu": "ÜN", "kategori": "Ekonomi",
        "baslik": "Küçük işletmeler ortak enerji alımıyla maliyeti azaltıyor",
        "ozet": "Aynı maliyet baskısı karşısında üç esnaf kooperatifi ortak tedarik ve verimlilik programı başlattı.",
        "cerceve": "uyum ve çözüm", "duygu": 0.42, "gorsel": "/assets/explore/15-market.jpg",
        "zaman": "24 dk", "alternatif_id": "enerji-a", "olgu_kodu": "enerji-kobi-1",
    },
    {
        "id": "uzay-a", "olay_id": "uzay", "birincil": True,
        "kaynak": "Bilim Akışı", "kaynak_kodu": "BA", "kategori": "Bilim",
        "baslik": "Araştırma uydusunun fırlatması teknik nedenle ertelendi",
        "ozet": "Ekip, son kontrollerde belirlenen sensör uyumsuzluğu nedeniyle fırlatma tarihini ileri aldı.",
        "cerceve": "aksama", "duygu": -0.31, "gorsel": "/assets/explore/06-space.jpg",
        "zaman": "43 dk", "alternatif_id": "uzay-b", "olgu_kodu": "uydu-erteleme-1",
    },
    {
        "id": "uzay-b", "olay_id": "uzay", "birincil": False,
        "kaynak": "Yarın Bilim", "kaynak_kodu": "YB", "kategori": "Bilim",
        "baslik": "Uydu ekibi sensör sorununu uçuş öncesinde yakaladı",
        "ozet": "Takvim ertelenirken erken tespit sayesinde riskli parça değiştirilecek ve test dizisi yeniden çalıştırılacak.",
        "cerceve": "güvenlik ve öğrenme", "duygu": 0.38, "gorsel": "/assets/explore/06-space.jpg",
        "zaman": "36 dk", "alternatif_id": "uzay-a", "olgu_kodu": "uydu-erteleme-1",
    },
    {
        "id": "egitim-a", "olay_id": "egitim", "birincil": True,
        "kaynak": "Kampüs Gündemi", "kaynak_kodu": "KG", "kategori": "Eğitim",
        "baslik": "Kütüphane yoğunluğu sınav haftasında iki katına çıktı",
        "ozet": "Öğrenciler akşam saatlerinde çalışma masası bulmakta zorlandıklarını söylüyor.",
        "cerceve": "kapasite sorunu", "duygu": -0.43, "gorsel": "/assets/explore/10-library.jpg",
        "zaman": "1 sa", "alternatif_id": "egitim-b", "olgu_kodu": "kutuphane-yogunluk-1",
    },
    {
        "id": "egitim-b", "olay_id": "egitim", "birincil": False,
        "kaynak": "Öğrenci Çözümleri", "kaynak_kodu": "ÖÇ", "kategori": "Eğitim",
        "baslik": "Kampüs, sınav yoğunluğu için üç yeni çalışma alanı açtı",
        "ozet": "Aynı yoğunluk verisinin ardından boş sınıflar gece çalışma alanına dönüştürüldü.",
        "cerceve": "yanıt ve erişim", "duygu": 0.48, "gorsel": "/assets/explore/10-library.jpg",
        "zaman": "48 dk", "alternatif_id": "egitim-a", "olgu_kodu": "kutuphane-yogunluk-1",
    },
    {
        "id": "saglik-a", "olay_id": "saglik", "birincil": True,
        "kaynak": "Sağlık Ajandası", "kaynak_kodu": "SA", "kategori": "Yaşam",
        "baslik": "Mevsimsel salgın nedeniyle polikliniklerde yoğunluk arttı",
        "ozet": "Bazı hastaneler başvurularda artış olduğunu ve bekleme sürelerinin uzadığını açıkladı.",
        "cerceve": "yoğunluk", "duygu": -0.58, "gorsel": "/assets/explore/07-lab.jpg",
        "zaman": "1 sa", "alternatif_id": "saglik-b", "olgu_kodu": "mevsimsel-salgin-1",
    },
    {
        "id": "saglik-b", "olay_id": "saglik", "birincil": False,
        "kaynak": "Koruyucu Yaşam", "kaynak_kodu": "KY", "kategori": "Yaşam",
        "baslik": "Yoğunluğa karşı hafta sonu danışma noktaları açılıyor",
        "ozet": "Aynı başvuru artışına yanıt olarak koruyucu bilgi ve yönlendirme noktalarının saatleri uzatıldı.",
        "cerceve": "koruyucu yanıt", "duygu": 0.29, "gorsel": "/assets/explore/07-lab.jpg",
        "zaman": "52 dk", "alternatif_id": "saglik-a", "olgu_kodu": "mevsimsel-salgin-1",
    },
    {
        "id": "spor-a", "olay_id": "spor", "birincil": True,
        "kaynak": "Saha Çizgisi", "kaynak_kodu": "SÇ", "kategori": "Spor",
        "baslik": "Genç takım finali son dakikada kaçırdı",
        "ozet": "Beraberlik golünün ardından gelen son hücum sonuç vermedi ve takım turnuvaya veda etti.",
        "cerceve": "sonuç", "duygu": -0.35, "gorsel": "/assets/explore/01-soccer.jpg",
        "zaman": "2 sa", "alternatif_id": "spor-b", "olgu_kodu": "genc-final-1",
    },
    {
        "id": "spor-b", "olay_id": "spor", "birincil": False,
        "kaynak": "Altyapı Günlüğü", "kaynak_kodu": "AG", "kategori": "Spor",
        "baslik": "Finali kaçıran genç takım sezonu gelişim rekoruyla kapattı",
        "ozet": "Aynı maçın ardından teknik ekip, kadrodaki sekiz oyuncunun üst yaş grubuna yükseldiğini duyurdu.",
        "cerceve": "gelişim", "duygu": 0.51, "gorsel": "/assets/explore/01-soccer.jpg",
        "zaman": "1 sa", "alternatif_id": "spor-a", "olgu_kodu": "genc-final-1",
    },
    {
        "id": "teknoloji-a", "olay_id": "teknoloji", "birincil": True,
        "kaynak": "Teknoloji Masası", "kaynak_kodu": "TM", "kategori": "Teknoloji",
        "baslik": "Açık kaynak projesinde kritik güvenlik açığı duyuruldu",
        "ozet": "Bakım ekibi belirli sürümlerde yetki kontrolünü etkileyen bir açık tespit etti.",
        "cerceve": "risk", "duygu": -0.67, "gorsel": "/assets/explore/05-circuit.jpg",
        "zaman": "2 sa", "alternatif_id": "teknoloji-b", "olgu_kodu": "acik-kaynak-yama-1",
    },
    {
        "id": "teknoloji-b", "olay_id": "teknoloji", "birincil": False,
        "kaynak": "Açık Kod", "kaynak_kodu": "AK", "kategori": "Teknoloji",
        "baslik": "Topluluk güvenlik açığı için doğrulanmış yamayı yayımladı",
        "ozet": "Aynı açık için güncelleme hazır; bakım ekibi etkilenen sürümleri ve geçiş adımlarını paylaştı.",
        "cerceve": "çözüm ve eylem", "duygu": 0.45, "gorsel": "/assets/explore/05-circuit.jpg",
        "zaman": "1 sa", "alternatif_id": "teknoloji-a", "olgu_kodu": "acik-kaynak-yama-1",
    },
    {
        "id": "kultur-a", "olay_id": "kultur", "birincil": True,
        "kaynak": "Kültür Rotası", "kaynak_kodu": "KR", "kategori": "Kültür",
        "baslik": "Mahalle sineması artan giderler nedeniyle kapanma riskiyle karşı karşıya",
        "ozet": "Bağımsız salon, izleyici sayısı korunsa da bakım ve enerji giderlerinin yükseldiğini açıkladı.",
        "cerceve": "kayıp riski", "duygu": -0.52, "gorsel": "/assets/explore/08-museum.jpg",
        "zaman": "3 sa", "alternatif_id": "kultur-b", "olgu_kodu": "mahalle-sinema-1",
    },
    {
        "id": "kultur-b", "olay_id": "kultur", "birincil": False,
        "kaynak": "Semt Dayanışması", "kaynak_kodu": "SD", "kategori": "Kültür",
        "baslik": "Mahalle sineması için üyelik kampanyası ilk hedefi geçti",
        "ozet": "Aynı maliyet sorunu sürerken yerel izleyicilerin başlattığı üyelik modeli ilk ay hedefini aştı.",
        "cerceve": "dayanışma", "duygu": 0.56, "gorsel": "/assets/explore/08-museum.jpg",
        "zaman": "2 sa", "alternatif_id": "kultur-a", "olgu_kodu": "mahalle-sinema-1",
    },
    {
        "id": "ulasim-a", "olay_id": "ulasim", "birincil": True,
        "kaynak": "Şehir Hattı", "kaynak_kodu": "ŞH", "kategori": "Kent",
        "baslik": "Banliyö hattındaki arıza sabah seferlerini aksattı",
        "ozet": "Sinyal sistemindeki arıza nedeniyle üç istasyonda bekleme süreleri uzadı.",
        "cerceve": "aksama", "duygu": -0.49, "gorsel": "/assets/explore/20-train.jpg",
        "zaman": "4 sa", "alternatif_id": "ulasim-b", "olgu_kodu": "banliyo-ariza-1",
    },
    {
        "id": "ulasim-b", "olay_id": "ulasim", "birincil": False,
        "kaynak": "Ulaşım İzleme", "kaynak_kodu": "Uİ", "kategori": "Kent",
        "baslik": "Banliyö arızasında yedek sinyal planı devreye alındı",
        "ozet": "Aynı arıza için ekipler yedek işletim planına geçti; sefer aralıkları kademeli olarak normale dönüyor.",
        "cerceve": "iyileşme", "duygu": 0.32, "gorsel": "/assets/explore/20-train.jpg",
        "zaman": "3 sa", "alternatif_id": "ulasim-a", "olgu_kodu": "banliyo-ariza-1",
    },
    {
        "id": "tarim-a", "olay_id": "tarim", "birincil": True,
        "kaynak": "Toprak Haber", "kaynak_kodu": "TH", "kategori": "Çevre",
        "baslik": "Kurak dönem yerel üreticinin hasat beklentisini düşürdü",
        "ozet": "Yağışların mevsim ortalamasının altında kalması bazı ürünlerde verim tahminini etkiledi.",
        "cerceve": "iklim baskısı", "duygu": -0.61, "gorsel": "/assets/explore/11-mountains.jpg",
        "zaman": "5 sa", "alternatif_id": "tarim-b", "olgu_kodu": "kuraklik-hasat-1",
    },
    {
        "id": "tarim-b", "olay_id": "tarim", "birincil": False,
        "kaynak": "Üreten Köy", "kaynak_kodu": "ÜK", "kategori": "Çevre",
        "baslik": "Üreticiler kurak dönemde damla sulama paylaşım ağı kurdu",
        "ozet": "Aynı düşük yağış koşullarında kooperatif, su tüketimini azaltan ekipmanı ortak kullanıma açtı.",
        "cerceve": "uyum", "duygu": 0.41, "gorsel": "/assets/explore/11-mountains.jpg",
        "zaman": "4 sa", "alternatif_id": "tarim-a", "olgu_kodu": "kuraklik-hasat-1",
    },
    {
        "id": "robotik-a", "olay_id": "robotik", "birincil": True,
        "kaynak": "Gelecek Teknoloji", "kaynak_kodu": "GT", "kategori": "Teknoloji",
        "baslik": "Öğrenci robotik takımının yarışma bütçesi eksik kaldı",
        "ozet": "Takım, prototip hazır olmasına rağmen yol ve parça giderleri için ek kaynak arıyor.",
        "cerceve": "kaynak sorunu", "duygu": -0.38, "gorsel": "/assets/explore/18-robot.jpg",
        "zaman": "6 sa", "alternatif_id": "robotik-b", "olgu_kodu": "robotik-butce-1",
    },
    {
        "id": "robotik-b", "olay_id": "robotik", "birincil": False,
        "kaynak": "Genç Üreticiler", "kaynak_kodu": "GÜ", "kategori": "Teknoloji",
        "baslik": "Yerel atölyeler robotik takımının parça ihtiyacını üstlendi",
        "ozet": "Aynı bütçe açığı için dört atölye malzeme desteği verdi; ekip yol giderleri için kampanyayı sürdürüyor.",
        "cerceve": "işbirliği", "duygu": 0.58, "gorsel": "/assets/explore/18-robot.jpg",
        "zaman": "5 sa", "alternatif_id": "robotik-a", "olgu_kodu": "robotik-butce-1",
    },
]

