"""NSosyal demo topluluk akışı: özgün, birinci tekil şahıs örnek postlar.

Bu metinler gerçek sosyal medya kullanıcılarından alınmamıştır. Her biri demoda
doğal bir sosyal akış ve farklı duygu tonları göstermek için proje içinde yazıldı.
"""

_SESler = {
    "denizcetin": [
        ("teknoloji", "Bugün eski tabletimi ikinci ekran yaptım. Masada yer açılması beklediğimden daha iyi hissettirdi."),
        ("bilim", "Akşam gökyüzü bulutsuzdu; dürbünle baktığım ilk yıldızı hâlâ bulamadım ama denemek güzeldi."),
        ("teknoloji", "Küçük bir hatayı çözmek için üç saat harcadım. Çözümün tek satır çıkması klasik ama yine de sevindirdi."),
        ("bilim", "Laboratuvar turunda en çok sessizlik şaşırttı beni. Her yerde küçük bir şeyin peşindelerdi."),
        ("teknoloji", "Açık kaynak notlarımı düzenledim; başkasının işine yarar mı bilmiyorum ama paylaşmak iyi geldi."),
        ("bilim", "Bugün öğrendiğim şey: bazı soruların cevabı yok gibi görünmesi, yanlış soru sorduğumuz anlamına geliyormuş."),
        ("teknoloji", "Telefonu bir saatliğine başka odaya bıraktım. Bildirim sesi olmadan çalışmak şaşırtıcı derecede kolaydı."),
        ("bilim", "Mikroskopta sıradan görünen bir damlanın içi bambaşka bir dünyaymış."),
        ("teknoloji", "Yeni uygulamayı ilk kez bir arkadaşım denedi. 'Buraya basınca ne oluyor?' sorusu en iyi testmiş."),
        ("bilim", "Kütüphaneden aldığım uzay kitabını bitiremedim ama içindeki çizimlere uzun uzun baktım."),
        ("teknoloji", "Kod yazarken müzik seçmekten daha çok zaman harcadığım günlerden biri."),
        ("bilim", "Bir deney başarısız oldu; notlarım ise ilk kez gerçekten işe yaradı."),
        ("teknoloji", "Klavye kısayollarını öğrenmeye çalışıyorum. Küçük kazanımlar günün temposunu değiştiriyor."),
        ("bilim", "Bugün bir kuşun göç rotasını anlatan kısa bir belgesel izledim. Haritaya tekrar tekrar döndüm."),
        ("teknoloji", "Eski bilgisayarı temizleyip yeniden açtım. Hâlâ çalışması biraz umut verdi."),
        ("bilim", "Merak etmek için büyük bir keşif gerekmiyormuş; iyi bir soru yetiyor."),
    ],
    "eceyilmaz": [
        ("sanat", "Sergide en sevdiğim tablo küçücük bir köşedeydi. Kalabalık geçip giderken ben biraz daha kaldım."),
        ("seyahat", "Sahile erken indim; kahve soğudu ama denizin sesi bütün planı değiştirdi."),
        ("sanat", "Bugün renk seçemeyince her şeyi masaya yaydım. Dağınıklık bazen iyi bir başlangıçmış."),
        ("seyahat", "Yeni bir sokaktan yürüdüm. Aynı şehirde kaybolmak için biraz yavaşlamak yetiyormuş."),
        ("sanat", "Konser çıkışında herkes aynı şarkıyı mırıldanıyordu. O anın uzamasını istedim."),
        ("seyahat", "Trende cam kenarı boştu. Yolculuğun yarısını dışarıyı izleyerek geçirdim."),
        ("sanat", "Bir arkadaşımın fotoğrafını çektim, o da beni çekerken yakaladı. Günün en doğal karesi o oldu."),
        ("seyahat", "Haritada işaretlemediğim bir kafeye oturdum. En güzel keşifler biraz plansız oluyor."),
        ("sanat", "Eski bir kitabın arasından kurumuş bir çiçek çıktı. Hikâyesini bilmemek hoşuma gitti."),
        ("seyahat", "Yağmur başlayınca yürüyüşü bırakmadım. Şehrin renkleri ıslakken daha sakin görünüyor."),
        ("sanat", "Atölyede herkes kendi işiyle uğraşıyordu ama aynı masada olmak iyi geldi."),
        ("seyahat", "Bugün sadece iki durak gittim, yine de sanki küçük bir tatile çıkmış gibiydim."),
        ("sanat", "Bir şarkının girişini tekrar tekrar dinledim. Bazen sözlerden önce ses anlatıyor."),
        ("seyahat", "Kıyıdaki taşları toplamadım, sadece fotoğraflarını çektim. Yerinde kalmaları daha doğru geldi."),
        ("sanat", "Not defterimin ilk sayfasını bozma korkusunu sonunda bıraktım."),
        ("seyahat", "Dönüş yolunda hiç acelem yoktu. Bu hissi biraz daha saklamak istiyorum."),
    ],
    "ardaatlas": [
        ("spor", "Koşuya çıkmak için çok isteksizdim; ilk beş dakikadan sonra fikrim tamamen değişti."),
        ("oyun", "Dün akşam arkadaşlarla eski bir oyuna döndük. Grafikler yaşlanmış, rekabet hiç yaşlanmamış."),
        ("spor", "Maç bittiğinde skor değil, son dakikadaki dayanışma aklımda kaldı."),
        ("oyun", "Yeni bölümü geçemedim ama taktik konuşması oyunun kendisinden daha eğlenceliydi."),
        ("spor", "Bugün rekor kırmadım. Yine de antrenmanı yarıda bırakmamış olmak yeterli."),
        ("oyun", "Ekran başında fazla kaldığımı fark edip dışarı çıktım. Hava beklediğimden daha iyiydi."),
        ("spor", "Mahalle sahasında tanımadığım insanlarla takım olduk. İlk isimleri maç sonunda öğrendim."),
        ("oyun", "Bir oyunun müziği bütün akşam kafamda kaldı. Bazen en iyi detay en görünmeyen oluyor."),
        ("spor", "Esnemeyi atladığım günün ertesi sabahı bana gerekli dersi verdi."),
        ("oyun", "Arkadaşımın yaptığı küçük oyunu denedim. Eksikleri vardı ama fikri çok samimiydi."),
        ("spor", "Yağmurda yürümek antrenman sayılır mı? Bugün sayılır."),
        ("oyun", "Kaybedince biraz sustuk, sonra aynı ekranda yeniden başladık."),
        ("spor", "Birinin ilk golünü atmasına şahit olmak, kendi golünden daha çok sevindirdi."),
        ("oyun", "Hafta sonu için oyun listesi yaparken yarısını nostalji seçti."),
        ("spor", "Bugün sadece on dakika hareket ettim. Sıfırdan iyidir."),
        ("oyun", "Zor bir bölümü geçmek için internete bakmadım. Sonunda bulunca daha çok sevindim."),
    ],
    "selinkaya": [
        ("egitim", "Kütüphanede herkesin aynı anda sayfa çevirmesi garip biçimde motive edici."),
        ("saglik", "Öğle arasında yaptığım kısa yürüyüş, öğleden sonrayı biraz daha hafif geçirmemi sağladı."),
        ("egitim", "Bugün notlarımı renk kodlamayı bıraktım. Sade hâliyle daha çok okuyabildim."),
        ("saglik", "Sabah su içmeyi unutmuştum; masaya şişe koymak basit ama etkili bir fikir."),
        ("egitim", "Sunumdan önce sesli prova yaptım. Kendi sesime alışmak stresi azalttı."),
        ("saglik", "Akşam ekranı biraz erken kapatınca uykuya dalmak sandığım kadar zor olmadı."),
        ("egitim", "Bir arkadaşımın sorusunu anlatırken konuyu ben de daha iyi anladım."),
        ("saglik", "Bugün kendime uzun bir liste yazmadım. Yapabildiğim üç şey yeterliydi."),
        ("egitim", "Kampüsteki yeni kulüp standlarını gezdim; beklemediğim bir atölyeye kayıt oldum."),
        ("saglik", "Pencereden gelen hava bile çalışma masasını değiştirebiliyormuş."),
        ("egitim", "Sınav haftası yaklaşırken en iyi planın arkadaşlarla aynı masada çalışmak olduğuna karar verdim."),
        ("saglik", "Bugün yavaş bir kahvaltı yaptım. Günün geri kalanı da buna uydu."),
        ("egitim", "Okuduğum makalede tek bir cümlenin altını çizdim; bütün nottan daha çok aklımda kaldı."),
        ("saglik", "Telefonu sessize alınca odadaki küçük sesleri fark ettim."),
        ("egitim", "Bir işi bitirmeden diğerine geçmemeyi deniyorum. Şimdilik işe yarıyor."),
        ("saglik", "Bugün kendime nazik davranmayı yapılacaklar listesine ekledim."),
    ],
    "mertdemir": [
        ("gundem", "Mahalle pazarında herkes aynı domatesin fiyatını konuşuyordu. Küçük sohbetler bile şehrin nabzını tutuyor."),
        ("ekonomi", "Köşedeki dükkânın yeni sahibi adımı hatırladı. Yerel esnafın en iyi tarafı bu."),
        ("gundem", "Parktaki banklardan biri yenilenmiş. Küçük değişiklikler bazen en çok fark edilen oluyor."),
        ("ekonomi", "Bugün alışveriş listesi yapmadan çıktım; dönüşte neden liste yaptığımı hatırladım."),
        ("gundem", "Otobüste bir çocuk bütün yol boyunca camdaki damlaları saydı. Şehir biraz yavaşladı."),
        ("ekonomi", "İkinci el pazarda aradığım lambayı bulamadım ama iyi bir kitapla döndüm."),
        ("gundem", "Sokak müzisyeni aynı şarkıyı iki kez çaldı, kimse rahatsız olmadı."),
        ("ekonomi", "Kahveyi evde yapmak küçük bir ritüele dönüştü. Hesabı da biraz rahatlatıyor."),
        ("gundem", "Semt kütüphanesinin çalışma saatleri uzamış. Akşam uğramak için iyi bir bahane."),
        ("ekonomi", "Pazarda mevsim meyvesi seçmek, fiyat tablosundan daha anlaşılır geliyor."),
        ("gundem", "Yağmurdan sonra kaldırımda oluşan küçük göletler çocuklar için ayrı bir gündemmiş."),
        ("ekonomi", "Bir tamirci, değiştirmenin değil onarmanın daha iyi olduğunu yine hatırlattı."),
        ("gundem", "Bugün herkes biraz aceleydi; kapıyı tutan birinin gülümsemesi bütün havayı değiştirdi."),
        ("ekonomi", "Mahalledeki kitap takasında verdiğim kitabın yerine daha önce aradığım bir kitap geldi."),
        ("gundem", "Akşamüstü meydanda oturup insanları izlemek, günün en iyi haber bülteni olabilir."),
        ("ekonomi", "Küçük üreticilerin standından aldığım ekmek, eve kadar dayanmadı."),
    ],
}

TOPLULUK_GONDERILERI = [
    {"id": 171 + index, "konu": konu, "metin": metin, "yazar": yazar}
    for yazar, gonderiler in _SESler.items()
    for index, (konu, metin) in enumerate(gonderiler, start=sum(len(x) for key, x in list(_SESler.items())[:list(_SESler).index(yazar)]))
]
